apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: canary-cloud-deployment
description: frontend pipeline
serialPipeline:
  stages:
  - targetId: online-boutique-cluster
    profiles: []
    strategy:
      canary:
        runtimeConfig:
          kubernetes:
            gatewayServiceMesh:
              httpRoute: "frontend-httproute"
              service: "frontend"
              deployment: "frontend"
        customCanaryDeployment:
          phaseConfigs: 
          - phaseId: "canary-25"
            percentage: 25
            profiles: []
            verify: true
          - phaseId: "stable"
            percentage: 100
            profiles: []
            verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: online-boutique-cluster
description: Online Boutique GKE cluster
gke:
 cluster: projects/cloud-computing-lab-1-402606/locations/europe-west6-a/clusters/online-boutique